services:
  tulip_app:
    container_name: tulip_app
    image: ggsheet/tulip_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env.docker
    ports: 
      - "8080:8080"
    depends_on:
      - tulip_db

  tulip_db:
    container_name: tulip_db
    image: postgres:16
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
    command: bash -c "chmod 600 /etc/ssl/private/server.key && chmod 644 /etc/ssl/certs/server.crt && postgres -D /var/lib/postgresql/data -c 'ssl=on' -c 'ssl_cert_file=/etc/ssl/certs/server.crt' -c 'ssl_key_file=/etc/ssl/private/server.key'"
    user: postgres

volumes:
  pgdata:
