services:
  tulip_app:
    container_name: tulip_app
    image: ggsheet/tulip_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env.docker
    ports: 
      - "8080:8080"
    depends_on:
      - tulip_db

  tulip_db:
    container_name: tulip_db
    image: postgres:16
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server.crt:/var/lib/postgresql/data/server.crt
      - ./server.key:/var/lib/postgresql/data/server.key

volumes:
  pgdata:
