// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CartInfo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<aside id=\"cartInfo\" class=\"cart_container\" style=\"display: none;\"><div class=\"cart_payment\"><div class=\"cart_head\"><h2>Detalles del pedido</h2></div><div id=\"cartPayment\" class=\"payment_breakdown\"><div class=\"payment_amount\"><h5>Subtotal</h5><h6 id=\"cartSub\" class=\"payment_price\"></h6></div><div class=\"payment_amount\"><h5>Envío</h5><h6 id=\"cartShip\" class=\"payment_price\"></h6></div><hr><div class=\"payment_amount\"><h5>Total</h5><h6 id=\"cartTotal\" class=\"payment_price\"></h6></div></div><div class=\"payment_button\"><button>Ir a Pagar</button></div></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
