// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"login_container\"><form id=\"loginForm\" method=\"POST\" action=\"/login\" novalidate class=\"form_wrapper\"><p class=\"section_title\">Iniciar sesión</p><fieldset class=\"field_section\"><div class=\"field_wrapper login_check\"><label for=\"adminEmail\">Correo Electrónico</label> <input type=\"email\" id=\"adminEmail\" name=\"adminEmail\" autocomplete=\"email\" onkeydown=\"return event.key != 'Enter';\" class=\"email_input\"><p id=\"loginErrorE\" class=\"helper_text error_message normal_size\"></p></div><div class=\"field_wrapper login_check\"><label for=\"adminPassword\">Contraseña</label> <input type=\"password\" id=\"adminPassword\" name=\"adminPassword\" autocomplete=\"current-password\" onkeydown=\"return event.key != 'Enter';\" required class=\"email_input\"><p id=\"loginErrorP\" class=\"helper_text error_message normal_size\"></p></div></fieldset><div class=\"form_btns\"><button type=\"submit\" id=\"loginBtn\" class=\"form_btn spinner\">Login</button><p id=\"loginError\" class=\"helper_text error_message normal_size\"></p></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
