// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"nav_container\"><div class=\"nav_content\"><div><a href=\"/\"><img src=\"https://kerigmalife.s3.us-east-2.amazonaws.com/logos/logo-h-reg.webp\"></a></div><ul><li class=\"nav_tab\"><a href=\"/\" class=\"nav_link\">Inicio</a></li><li class=\"nav_tab\"><a href=\"/store\" class=\"nav_link\">Tienda</a></li><li class=\"nav_tab\"><a href=\"/articles\" class=\"nav_link\">Artículos</a></li><li class=\"nav_tab\"><a href=\"/resources\" class=\"nav_link\">Recursos</a></li><li class=\"nav_tab\"><a href=\"/cart\" class=\"cart_link\"><img src=\"public/icons/cart.svg\"><div class=\"cart_amount\"><p>0</p></div></a></li><li class=\"nav_tab\"><input type=\"checkbox\" id=\"drawerToggle\"> <label class=\"drawer_link\" for=\"drawerToggle\"><svg viewBox=\"0 0 32 32\"><path class=\"line line-top-bottom\" d=\"M27 10 13 10C10.8 10 9 8.2 9 6 9 3.5 10.8 2 13 2 15.2 2 17 3.8 17 6L17 26C17 28.2 18.8 30 21 30 23.2 30 25 28.2 25 26 25 23.8 23.2 22 21 22L7 22\"></path> <path class=\"line\" d=\"M7 16 27 16\"></path></svg></label><div class=\"drawer_content\"><ul><li><a href=\"/\">Inicio</a></li><hr><li><a href=\"/store\">Tienda</a></li><hr><li><a href=\"/articles\">Artículos</a></li><hr><li><a href=\"/resources\">Recursos</a></li><hr><li><a href=\"/cart\">Carrito</a></li><hr></ul></div></li></ul></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
